### ISSUE TITLE
improve usability for TEPIC

### ISSUE THREAD

**Issue by SchulzLab** [SchulzLab/TEPIC#13]
While using the TEPIC command line I have the following ideas for improvement:

* currently the software only works when one runs the TEPIC.sh file within the TEPIC/Code directory (or something is not properly documented). It would be great to change as such, that one can run it from everywhere, for example once the TEPIC/Code folder was added to PATH
* I think it would make sense to move the matrices to a separate folder (maybe PWMs in the top folder). Right now they are somewhat hidden
* add an explicit Installation part to the README, right now it is hidden in the Using TEPIC section

**Comment by Florian411** [comment]
I implemented the points you mentioned.

**Comment by SchulzLab** [comment]
Great thanks Florian!
