### ISSUE TITLE
Cleanup incomplete

### ISSUE THREAD

**Issue by ghost** [SchulzLab/TEPIC#15]
Hi,
the following could be improved:
- after successful run: remove the `*_sorted.bed` files
- after failed run: remove everything, i.e., the `*.amd.tsv` and the `*.OpenChromatin.fasta` are left behind

- after successful run: consider gzipping the affinity output file(s) to save some space and potentially add a column to the `*_Scaled_Affinity.txt` file containing the scale factors instead of having both the original `*_Affinity.txt` and the `*_Scaled_Affinity.txt` files

Best,
Peter

**Comment by Florian411** [comment]
Hey,
Thanks for the suggestions.
Point1 : Done
Point 2: The OpenChromatin.fasta will be deleted now. The amd.tsv stays, as I think it might help to reproduce the potential error
Point 3: There is an option now to zip the files.
