### ISSUE TITLE
Can't locate elastic net model source code

### ISSUE THREAD

**Issue by Prayforhanluo** [SchulzLab/TEPIC#16]
Hey, great work. The linear model seems like a great idea.
       I can't seem to find the actual code about the model here though? 
       Am I missing something?

**Comment by Florian411** [comment]
Hey,
Thanks! The repository currently contains TEPIC, which is just about computing the TF features. 
We are currently working on a script that can be used to run both the TF annotation as well as the Elastic net regression and produces Figures for model interpretation. This will be added to the repository as soon as possible.

**Comment by Florian411** [comment]
The code for running the linear model is now included.
