### ISSUE TITLE
runDYNAMITE.sh parallel processes

### ISSUE THREAD

**Issue by ghost** [SchulzLab/TEPIC#22]
Running the DYNAMITE pipeline in parallel (A vs B and A vs C) on several servers that share the same file system leads to interference on the file system level as several temporary files (stuff like `_peaks_temp.bed` or `tempFasta.bed`) are created in the same directory w/o using proper temporary file/folder names and thus may be deleted by another process, resulting in things like
```bash
rm: cannot remove `tempFasta.bed': No such file or directory
```

**Comment by Florian411** [comment]
There was indeed one file without a unique identifier in the TEPIC pipeline. Please try again. However, there are no files called `_peaks_temp.bed `or` tempFasta.bed` being generated anywhere, so if the problem still exists we might have to look at your particular use case.

**Comment by ghost** [comment]
I don't think so, if I search for `tempFasta.bed`, I find that file to be generated in `TEPIC.sh` - I thought running the full DYNAMITE pipeline implies a run of TEPIC as well?

**Comment by Florian411** [comment]
Found and fixed! Thanks for pointing it out!.
