### ISSUE TITLE
TEPIC.sh prefix wrong

### ISSUE THREAD

**Issue by ghost** [SchulzLab/TEPIC#23]
I just pulled the latest master and now TEPIC fails when it is attempting to remove files names like this [shortened]
```bash
... /group2/E114_dnase_peaks_TEPIC_08_29_17_10_53_51_596909095_/TL/deep/fhgfs/projects/pebert/ ...
```
Obviously, there is something wrong about the concatenation of the datetime-based identifier and the path...

**Comment by Florian411** [comment]
Thanks, there was indeed a mixup introduced by the last change. It is corrected now.
