### ISSUE TITLE
computeMeanRatioTFAffinities is not Python3.x compliant

### ISSUE THREAD

**Issue by ghost** [SchulzLab/TEPIC#24]
This script contains a condition like `if dict.has_key(key):` several times; the attribute `has_key` has been removed in Python3.x - these calls need to be replaced with the common Python idiom `if key in dict:` to make the script Python3 compliant.

**Comment by Xethic** [comment]
Hi,

thanks for the clue. We are aware of several scripts that currently break a python 3.x compliance. While preparing the software for the next publication(s) we def. have this on our list. ( I guess python 2.x support runs out on 2021).

Best,

Fabian

**Comment by Florian411** [comment]
The has_key call is now replaced everywhere.
