### ISSUE TITLE
-r option causing TEPIC.sh to crash

### ISSUE THREAD

**Issue by CRoberto1926** [SchulzLab/TEPIC#25]
Hello,
I'm using the software on Drosophila with a custom set of PWMs, that I converted using PSCM_to_PSEM.cpp
I'm interested in using DREM, so I need to run TEPIC.sh with the -r option.
However, when I do so, I get the following:

Preprocessing region file: Removing chr prefix, sorting regions and removing duplicats
Generating random genomic regions
Results from chrom 4 saved
Traceback (most recent call last):
File "/home/roberto/Dropbox/phd_project_data/Ecdysone_timecourse_data/TEPIC_INVOKE_DYNAMITE_DREM/TEPIC/Code/findBackground.py", line 284, in find_background_regions               │                                                                                                                                                                                     
    matched = start_relaxed_search(kdtree, chrom_seq, taken, idxmap, data_limits, params)                                                                                            │                                                                                                                                                                                     
  File "/home/roberto/Dropbox/phd_project_data/Ecdysone_timecourse_data/TEPIC_INVOKE_DYNAMITE_DREM/TEPIC/Code/findBackground.py", line 206, in start_relaxed_search                  │                                                                                                                                                                                     
    cand_feat = compfeat(cand_seq)                                                                                                                                                   │                                                                                                                                                                                     
  File "/home/roberto/Dropbox/phd_project_data/Ecdysone_timecourse_data/TEPIC_INVOKE_DYNAMITE_DREM/TEPIC/Code/findBackground.py", line 168, in compute_seq_features                  │                                                                                                                                                                                     
    ft_pct_gc = np.round((num_g + num_c) / seq_len * 100., 2)                                                                                                                        │                                                                                                                                                                                     
ZeroDivisionError: float division by zero                                                                                                                                            │                                                                                                                                                                                     
Error processing chromosome 2LResults from chrom 2R saved                                                                                                                            │                                                                                                                                                                                     
Results from chrom 3R saved                                                                                                                                                          │                                                                                                                                                                                     
Results from chrom 3L saved                                                                                                                                                          │                                                                                                                                                                                     
Results from chrom X saved                                                                                                                                                           │                                                                                                                                                                                     
Runnig bedtools                                                                                                                                                                      │                                                                                                                                                                                     
Converting invalid characters                                                                                                                                                        │                                                                                                                                                                                     
Starting TRAP                                                                                                                                                                        │                                                                                                                                                                                     
Discretising TF affinities                                                                                                                                                           │                                                                                                                                                                                     
Error in x/y : non-numeric argument to binary operator                                                                                                                               │                                                                                                                                                                                     
Calls: apply -> FUN                                                                                                                                                                  │                                                                                                                                                                                     
Execution halted          

I will try to narrow down the problem, meanwhile I'm opening the issue.
Also, let me know if you need data for a reproducible example.

Best,
Roberto

**Comment by Florian411** [comment]
Hey,
Thanks for using the tool! If you could provide me with a set of regions (a bed file, can be a subset of the full set, but should still cover all chromosomes), and a link to the reference genome and the annotation file you are using, I will have a look as well.

Did you ensure that you are using the latest version of TEPIC?

**Comment by CRoberto1926** [comment]
Hi,
yes I'm using the latest version of TEPIC.
I'll send you a WeTransfer link to your MPI email with the data you need to reproduce this behaviour.
Let me know when it arrives, because currently we have issues with our emails.
Thanks for the help and the fast reply,
Roberto
