### ISSUE TITLE
Gene scores from TEPIC differ depending on Python version

### ISSUE THREAD

**Issue by JLGentry** [SchulzLab/TEPIC#31]
I have used the pipeline included in DYNAMITE to test the sample data with Python version 2.7 and 3.7, and I get different gene scores depending on the version. Peak_counts and Peak_length are the same however.

I made a few changes to the DYNAMITE config file to rerun the gene score calculation:
1) specified output folder name
2) changed coverage_Columns_Group1/2 to coverage_Column_Group1/2 since 'column' is singular in the bash script
3) assigned coverage_Columns_Group1/2 as "4"
4) specified path to gtf (downloaded from ftp://ftp.ensembl.org/pub/grch37/current/gtf/homo_sapiens/)
5) specified path to assembly (downloaded primary assembly from ftp://ftp.ensembl.org/pub/grch37/current/fasta/homo_sapiens/dna/)
6) commented out existing_TEPIC_Results_Group1/2

config file and example gene score outputs:
[DYNAMITE.cfg.txt](https://github.com/SchulzLab/TEPIC/files/3752129/DYNAMITE.cfg.txt)
[Hf03_BlEM_NOMe.python_2.7.Decay_Peak_Features_Affinity_Gene_View_Filtered.txt](https://github.com/SchulzLab/TEPIC/files/3752130/Hf03_BlEM_NOMe.python_2.7.Decay_Peak_Features_Affinity_Gene_View_Filtered.txt)
[Hf03_BlEM_NOMe.python_3.7.Decay_Peak_Features_Affinity_Gene_View_Filtered.txt](https://github.com/SchulzLab/TEPIC/files/3752131/Hf03_BlEM_NOMe.python_3.7.Decay_Peak_Features_Affinity_Gene_View_Filtered.txt)

**Comment by Florian411** [comment]
Thanks for spotting this. We have developed TEPIC using python 2.7, it seems that some part of the search is not working in 3.7, I'll look into it once I am free!

**Comment by Florian411** [comment]
I made changes to the code and changed the return of the map function. It should be fine now! Thanks again for spotting this.
