### ISSUE TITLE
Error not reported with subfolders in --outDir param from INVOKE.R

### ISSUE THREAD

**Issue by xpastor** [SchulzLab/TEPIC#33]
If the outDir param of the 'INVOKE.R' script contains subdirectories, the script neither creates the directory nor throws an error.

To overcome this, either 'recursive = TRUE' and 'showWarnings = FALSE' should be defined in dir.create(), or it should be stated in the documentation that the parameter does not accept subdirectories.

**Comment by Florian411** [comment]
Thanks for the feedback.
I've added the 'recursive=TRUE' setting to both INVOKE and DYNAMITE.
