### ISSUE TITLE
The motif length files have wrong indices

### ISSUE THREAD

**Issue by moritzschaefer** [SchulzLab/TEPIC#36]
In commit 7520518cc2f54c5a142924acb18ce6a8abf377c5 all motif-length files were destroyed

**Comment by Florian411** [comment]
Thanks for brining this up, I'll have a look at it.

**Comment by Florian411** [comment]
It seems this only affects the version 2.1 PWMs, until it is fixed, please stick to 2.0

**Comment by Florian411** [comment]
Has been fixed.
